services:
  - type: web
    name: agente-astrolaboral
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: SYSTEM_PROMPT_PATH
        value: prompts/system_es.txt
